# Generated by Django 5.2.17 on 2026-09-22 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('task_number', models.PositiveSmallIntegerField(default=2)),
                ('type', models.CharField(choices=[('agree_disagree', 'Agree or Disagree'), ('advantages_disadvantages', 'Advantages / Disadvantages'), ('discuss_both_views', 'Discuss Both Views'), ('problem_solution', 'Problem / Solution'), ('positive_negative', 'Positive or Negative Development'), ('task1_chart', 'Task 1 — Chart or Graph'), ('task1_process', 'Task 1 — Process'), ('task1_map', 'Task 1 — Map'), ('task1_letter', 'Task 1 — Letter (General Training)')], max_length=32)),
                ('prompt', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='writing/')),
                ('suggested_time_minutes', models.PositiveSmallIntegerField(default=40)),
                ('target_words', models.PositiveSmallIntegerField(default=250)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('reveal_policy', models.CharField(choices=[('always', 'Always available'), ('after_submission', 'Only after the student submits')], default='always', max_length=20)),
            ],
            options={
                'ordering': ('task_number', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='WritingModelAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('body', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_answers', to='writing.writingtask')),
            ],
            options={
                'ordering': ('task', 'order'),
            },
        ),
    ]
