# Generated by Django 5.2.17 on 2026-09-22 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Awaiting feedback'), ('graded', 'Graded')], db_index=True, default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('self_assessed_band', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('model_answer_revealed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='writing.writingtask')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='WritingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_achievement', models.DecimalField(decimal_places=1, max_digits=2)),
                ('coherence_cohesion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('lexical_resource', models.DecimalField(decimal_places=1, max_digits=2)),
                ('grammatical_range', models.DecimalField(decimal_places=1, max_digits=2)),
                ('overall', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.TextField(blank=True)),
                ('grader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='writing.writingsubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='writingsubmission',
            index=models.Index(fields=['status', '-submitted_at'], name='writing_wri_status_d0b273_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsubmission',
            index=models.Index(fields=['user', '-submitted_at'], name='writing_wri_user_id_3a8d40_idx'),
        ),
    ]
