# Generated by Django 5.2.17 on 2026-09-22 15:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('skill', models.CharField(db_index=True, max_length=16)),
                ('raw_total', models.PositiveSmallIntegerField(default=40, help_text='Number of questions the published table is defined over.')),
                ('is_default', models.BooleanField(default=False, help_text='Used by tests of this skill that do not name a scale.')),
                ('min_questions_for_confidence', models.PositiveSmallIntegerField(default=30, help_text='Attempts with fewer raw questions than this report a band range rather than a single band.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('skill', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('skill',), name='one_default_band_scale_per_skill')],
            },
        ),
        migrations.CreateModel(
            name='BandScaleRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_min', models.PositiveSmallIntegerField()),
                ('raw_max', models.PositiveSmallIntegerField()),
                ('band', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('9.0'))])),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='grading.bandscale')),
            ],
            options={
                'ordering': ('scale', 'raw_min'),
                'constraints': [models.UniqueConstraint(fields=('scale', 'raw_min'), name='unique_row_start_per_scale'), models.CheckConstraint(condition=models.Q(('raw_max__gte', models.F('raw_min'))), name='band_row_max_gte_min')],
            },
        ),
    ]
