# Generated by Django 5.2.17 on 2026-09-22 15:40

import apps.content.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('number', models.PositiveSmallIntegerField(help_text='Display number within the whole test; recomputed on publish.')),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Shown only in the post-submission review payload.')),
            ],
            options={
                'ordering': ('test', 'number'),
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(choices=[('tfng', 'True / False / Not Given'), ('mcq', 'Multiple choice'), ('gap', 'Gap fill'), ('matching', 'Matching')], max_length=16)),
                ('instructions', models.TextField(blank=True)),
                ('options_scope', models.CharField(choices=[('per_question', 'Per question'), ('shared', 'Shared pool')], default='per_question', max_length=16)),
                ('match_mode', models.CharField(choices=[('exact', 'Exact'), ('normalized', 'Normalized')], default='exact', max_length=16)),
                ('allow_article_omission', models.BooleanField(default=False)),
                ('allow_plural_variants', models.BooleanField(default=False, help_text='Off by default: real IELTS marks a singular/plural mismatch wrong. Prefer adding an explicit accepted answer.')),
            ],
            options={
                'ordering': ('section', 'order'),
            },
        ),
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.content.models.audio_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=80)),
                ('size_bytes', models.PositiveIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64, unique=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('label', models.CharField(blank=True, max_length=8)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.question')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.questiongroup')),
            ],
            options={
                'ordering': ('group', 'question', 'order'),
            },
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Authoritative answer string.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('option', models.ForeignKey(blank=True, help_text="Set when the group's type draws from an option set.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to='content.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to='content.question')),
            ],
            options={
                'ordering': ('question', 'order'),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.questiongroup'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('audio_start_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('playback_policy', models.CharField(choices=[('free', 'Free playback'), ('once_no_seek', 'Play once, no seeking')], default='free', max_length=16)),
                ('transcript_visibility', models.CharField(choices=[('during_test', 'Visible during the test'), ('after_submit', 'Visible after submission'), ('never', 'Never shown')], default='during_test', help_text='Once real audio is attached, showing the transcript during the test turns a listening test into a reading test.', max_length=16)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='content.audioasset')),
            ],
            options={
                'ordering': ('test', 'order'),
            },
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='content.section'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('text', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='content.section')),
            ],
            options={
                'ordering': ('section', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening')], db_index=True, max_length=16)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('time_limit_minutes', models.PositiveSmallIntegerField()),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_payload', models.JSONField(blank=True, editable=False, null=True)),
                ('payload_etag', models.CharField(blank=True, editable=False, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('band_scale', models.ForeignKey(blank=True, help_text='Leave empty to use the default scale for this skill.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.bandscale')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('skill', 'title'),
            },
        ),
        migrations.AddField(
            model_name='section',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.test'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.test'),
        ),
        migrations.AddConstraint(
            model_name='questiongroup',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='unique_group_order_per_section'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='unique_block_order_per_section'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['skill', 'status'], name='content_tes_skill_5ec563_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('test', 'order'), name='unique_section_order_per_test'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('group', 'order'), name='unique_question_order_per_group'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('test', 'number'), name='unique_question_number_per_test'),
        ),
    ]
