# Generated by Django 5.2.17 on 2026-10-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='heading',
            field=models.TextField(blank=True),
        ),
    ]
