# Generated by Django 5.2.17 on 2026-10-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_questiongroup_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='kind',
            field=models.CharField(choices=[('paragraph', 'Paragraph'), ('heading', 'Heading'), ('rule', 'Divider')], default='paragraph', max_length=16),
        ),
        migrations.AlterField(
            model_name='block',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
