# Generated by Django 5.2.17 on 2026-10-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_block_kind_alter_block_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='kind',
            field=models.CharField(choices=[('paragraph', 'Paragraph'), ('section', 'Title'), ('heading', 'Heading'), ('rule', 'Divider')], default='paragraph', max_length=16),
        ),
    ]
