# Generated by Django 5.2.17 on 2026-09-22 15:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('grading', '0002_seed_band_scales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('test_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('expired', 'Submitted after time expired'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('raw_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('band', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('band_low', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('band_high', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('band_confidence', models.CharField(default='low', max_length=8)),
                ('band_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grading.bandscale')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='content.test')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField()),
                ('question_type', models.CharField(max_length=16)),
                ('raw_value', models.TextField(blank=True)),
                ('normalized_value', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_spent_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.option')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.testattempt')),
            ],
            options={
                'ordering': ('attempt', 'question_number'),
            },
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', '-submitted_at'], name='attempts_te_user_id_cafff9_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', '-submitted_at'], name='attempts_te_test_id_dba378_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['status', 'expires_at'], name='attempts_te_status_ba357b_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_attempt_question'),
        ),
    ]
