# Generated by Django 5.2.17 on 2026-09-22 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SpeakingCueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prep_seconds', models.PositiveSmallIntegerField(default=60)),
                ('speak_seconds', models.PositiveSmallIntegerField(default=120)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cue_card', to='speaking.speakingtopic')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.PositiveSmallIntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3')])),
                ('kind', models.CharField(choices=[('question', 'Question'), ('bullet', 'Cue card bullet'), ('phrase', 'Useful phrase')], max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('text', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='speaking.speakingtopic')),
            ],
            options={
                'ordering': ('topic', 'part', 'kind', 'order'),
                'constraints': [models.UniqueConstraint(fields=('topic', 'part', 'kind', 'order'), name='unique_speaking_item_slot')],
            },
        ),
    ]
