# Generated by Django 5.2.17 on 2026-09-22 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_payload', models.JSONField(blank=True, editable=False, null=True)),
                ('payload_etag', models.CharField(blank=True, editable=False, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headword', models.CharField(max_length=80)),
                ('pos', models.CharField(choices=[('noun', 'noun'), ('verb', 'verb'), ('adjective', 'adjective'), ('adverb', 'adverb'), ('phrase', 'phrase'), ('phrasal verb', 'phrasal verb')], max_length=20)),
                ('definition', models.TextField()),
                ('example', models.TextField(help_text='Must contain exactly one **bolded** span, which is the word in context.')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabulary.vocabularysection')),
            ],
            options={
                'ordering': ('section', 'order'),
                'constraints': [models.UniqueConstraint(fields=('section', 'headword'), name='unique_headword_per_section')],
            },
        ),
    ]
