# Generated by Django 5.2.17 on 2026-09-22 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=8)),
                ('interval_before', models.PositiveSmallIntegerField()),
                ('interval_after', models.PositiveSmallIntegerField()),
                ('reviewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_reviews', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocabularyword')),
            ],
            options={
                'ordering': ('-reviewed_at',),
            },
        ),
        migrations.CreateModel(
            name='VocabularyReviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.PositiveSmallIntegerField(default=1)),
                ('due_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('last_rating', models.CharField(blank=True, max_length=8)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_states', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_states', to='vocabulary.vocabularyword')),
            ],
            options={
                'ordering': ('due_at',),
                'indexes': [models.Index(fields=['user', 'due_at'], name='vocabulary__user_id_247b3c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'word'), name='unique_review_state_per_word')],
            },
        ),
    ]
