# Generated by Django 5.2.17 on 2026-09-22 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('metric_key', models.CharField(max_length=48)),
                ('dimension_key', models.CharField(blank=True, max_length=64)),
                ('value_int', models.IntegerField(default=0)),
                ('value_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ('-date', 'metric_key'),
                'constraints': [models.UniqueConstraint(fields=('date', 'metric_key', 'dimension_key'), name='unique_metric_per_day')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=48)),
                ('anon_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=32)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('skill', models.CharField(blank=True, max_length=16)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('ua_family', models.CharField(blank=True, max_length=40)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['name', 'occurred_at'], name='analytics_e_name_a15d8e_idx'), models.Index(fields=['user', 'occurred_at'], name='analytics_e_user_id_2fcb42_idx'), models.Index(fields=['object_type', 'object_id', 'occurred_at'], name='analytics_e_object__daed7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('seen', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='content.question')),
            ],
            options={
                'ordering': ('accuracy',),
                'constraints': [models.UniqueConstraint(fields=('question', 'date'), name='unique_question_stat_per_day')],
            },
        ),
        migrations.CreateModel(
            name='TestStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('completions', models.PositiveIntegerField(default=0)),
                ('avg_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('median_duration_s', models.PositiveIntegerField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='content.test')),
            ],
            options={
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('test', 'date'), name='unique_test_stat_per_day')],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('best_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('latest_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('avg_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'skill'),
                'constraints': [models.UniqueConstraint(fields=('user', 'skill'), name='unique_progress_per_skill')],
            },
        ),
    ]
